### ISSUE TITLE
[ANY EPIC] use typeahead to help user to have smart filtering 

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-012#85]
As Valerii proposed: to implement filters like here (in GitHub)
`is:open is:issue label:blocked`

we can use [typeahead](https://angular-ui.github.io/bootstrap/#/typeahead) to help user at the every moment of input (proposing only suitable info).

examples: 

1.`pri` will propose `priority`
2. `priority:` will propose `critical, high, normal, low`
3. `priority:low author:` will propose to chose someone among the team

The questions are: 
- can we use typeahead to choose several values (for example to display few priorities)
- can we have typeahead working with several dataset as in example 3

**Comment by vitalii-kozachok** [comment]
* can we use typeahead to choose several values (for example to display few priorities)
* can we have typeahead working with several dataset as in example 3

I'd say NO for both
but you can create custom directive with 2 typeeheads to handle it

**Comment by ITsvetkoFF** [comment]
@vitalii-kozachok  the main idea is that if there are many parameters to filter items (for example, 10), having 10 directives with typeaheads will be confusing. And it can be solved by some "smart filter" field.

overall the system of filtering items here in GitHub is nice. [but a bit complicated :smile: ](https://help.github.com/articles/searching-issues/)

**Comment by vitalii-kozachok** [comment]
You'll need two typeeheads only (for key and value). The one for value will depend on the key selected in first typeehead. After selecting both, combination will be added to filter. 
You can try to enchance [this directive](http://mbenford.github.io/ngTagsInput/)
But the problem here will be in combination of filter criterias. All of them will be combined with AND (OR) only. The second thing is that you'll check only if value "is equal". (no **>**, **<**, **!=**, **in**, etc.)
To have more flexibility you'll need something like [this](http://mfauveau.github.io/angular-query-builder/)

**Comment by vp9920** [comment]
Vitalii, the flexible thing, that you proposed looks too cumbersome as for me, and looking at it I have feelings similar to those, that I have looking at a big registration form, that I have fill in to continue.
I think it would be not so bad to show in first place hints for AND and "is equal" and in the end of the list hints for OR and <, >. Yes, I realize that using full flexibility of such filter, user's input will be similar to programming language condition sentence, but after all, every user of our tool IS a programmer.

**Comment by vp9920** [comment]
Am I right? Every tester is a programmer?
